-- =============================================================================
-- Migration 018 — Agent Soul Template
-- Adds a per-tenant generated agent soul template.
-- When a new customer is created, their soul_file is pre-populated from this.
-- Previously souls were hand-seeded; now they are generated from onboarding data.
-- =============================================================================

ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS agent_soul_template JSONB DEFAULT NULL;

-- agent_soul_template structure (generated by soulGenerator.js):
-- {
--   "base_identity": {
--     "agent_name": "Aria",
--     "organization": "Covenant Trust",
--     "role": "Personalized retirement planning assistant...",
--     "tone_description": "warm, professional, and reassuring"
--   },
--   "communication_style": {
--     "tone": "warm & professional",
--     "complexity_level": 3,
--     "language": "plain English",
--     "emotional_awareness": "high",
--     "key_principles": ["..."]
--   },
--   "generated_at": "2026-03-25T00:00:00Z",
--   "generated_from": { "company_name": "...", "vertical": "...", "agent_name": "..." }
-- }

COMMENT ON COLUMN tenants.agent_soul_template IS
  'Auto-generated agent soul. New customers get this pre-applied to their soul_file. Regenerated via POST /api/portal/settings/generate-soul.';
