-- Migration 021: Tenant webhook subscriptions
--
-- Allows tenants to register HTTPS endpoints that Shenmay will POST to
-- when specific events occur (new session, flag raised, session ended, etc.).
-- Each tenant can have up to 10 active webhooks.
--
-- Delivery model: fire-and-forget with one retry on failure.
-- Payload is signed with HMAC-SHA256 using the webhook secret so the
-- receiving server can verify the request came from Shenmay.

CREATE TABLE IF NOT EXISTS tenant_webhooks (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  -- Human-readable label (e.g. "CRM integration", "Slack alerts")
  label       TEXT NOT NULL DEFAULT 'Webhook',

  -- The URL Shenmay will POST to
  url         TEXT NOT NULL,

  -- HMAC-SHA256 signing secret — generated by Shenmay, shown once to tenant
  -- Stored hashed; raw value returned only at creation time
  secret_hash TEXT NOT NULL,

  -- Which events trigger this webhook (array of event type strings)
  -- Supported: session.started, session.ended, flag.created, customer.created, concern.raised
  event_types TEXT[] NOT NULL DEFAULT ARRAY['flag.created', 'concern.raised'],

  enabled     BOOLEAN NOT NULL DEFAULT TRUE,

  -- Delivery stats (updated after each attempt)
  last_triggered_at   TIMESTAMPTZ,
  last_success_at     TIMESTAMPTZ,
  last_failure_at     TIMESTAMPTZ,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,

  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tenant_webhooks_tenant ON tenant_webhooks(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_webhooks_enabled  ON tenant_webhooks(tenant_id, enabled);
