#!/bin/bash
# ============================================================
# Nomii AI — Self-Hosted Installer
# Interactive first-run setup wizard.
# Run: bash scripts/install.sh
# ============================================================

set -e

# Colour helpers
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT_DIR"

echo ""
echo -e "${BOLD}============================================================${NC}"
echo -e "${BOLD}  Nomii AI — Self-Hosted Setup${NC}"
echo -e "${BOLD}============================================================${NC}"
echo ""

# ------------------------------------------------------------
# Step 0: Prerequisites check
# ------------------------------------------------------------
echo -e "${BLUE}Checking prerequisites...${NC}"
echo ""

MISSING=0

if ! command -v docker &> /dev/null; then
  echo -e "  ${RED}✗ Docker not found${NC} — install from https://docs.docker.com/get-docker/"
  MISSING=1
else
  echo -e "  ${GREEN}✓ Docker $(docker --version | cut -d' ' -f3 | tr -d ',')${NC}"
fi

if ! docker compose version &> /dev/null; then
  echo -e "  ${RED}✗ Docker Compose v2 not found${NC} — update Docker Desktop or install the plugin"
  MISSING=1
else
  echo -e "  ${GREEN}✓ Docker Compose $(docker compose version --short)${NC}"
fi

if [ "$MISSING" -eq 1 ]; then
  echo ""
  echo -e "${RED}Please install the missing prerequisites and re-run this script.${NC}"
  exit 1
fi

echo ""

# ------------------------------------------------------------
# Step 1: Create .env if it doesn't exist
# ------------------------------------------------------------
if [ -f ".env" ]; then
  echo -e "${YELLOW}An existing .env file was found.${NC}"
  read -p "Overwrite it with a fresh setup? [y/N] " OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    echo "Keeping existing .env. Skipping configuration wizard."
    echo ""
    SKIP_CONFIG=1
  fi
fi

if [ "${SKIP_CONFIG}" != "1" ]; then
  echo -e "${BLUE}Let's configure Nomii AI.${NC}"
  echo -e "Press ${BOLD}Enter${NC} to accept the default shown in brackets."
  echo ""

  # --- Domain / URLs ---
  read -p "Public domain (e.g. nomii.example.com): " DOMAIN
  DOMAIN="${DOMAIN:-localhost}"
  if [ "$DOMAIN" = "localhost" ]; then
    APP_URL="http://localhost"
    PORTAL_URL="http://localhost"
  else
    APP_URL="https://${DOMAIN}"
    PORTAL_URL="https://${DOMAIN}"
  fi

  # --- Secrets ---
  echo ""
  echo -e "${YELLOW}Generating secure secrets...${NC}"
  JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64)
  WIDGET_JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64)
  API_KEY_ENCRYPTION_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64)
  DB_PASSWORD=$(openssl rand -hex 16 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 32)
  echo -e "  ${GREEN}✓ Secrets generated${NC}"

  # --- Anthropic API Key ---
  echo ""
  read -p "Anthropic API key (sk-ant-...): " ANTHROPIC_API_KEY

  # --- Master email ---
  echo ""
  read -p "Your admin email (gets unlimited master account): " MASTER_EMAIL

  # --- SMTP ---
  echo ""
  echo -e "${BLUE}Email / SMTP setup${NC} (required for notifications and invite emails)"
  read -p "  SMTP host [smtp.gmail.com]: " SMTP_HOST
  SMTP_HOST="${SMTP_HOST:-smtp.gmail.com}"
  read -p "  SMTP port [465]: " SMTP_PORT
  SMTP_PORT="${SMTP_PORT:-465}"
  read -p "  SMTP user: " SMTP_USER
  read -s -p "  SMTP password: " SMTP_PASS
  echo ""
  read -p "  From address [noreply@${DOMAIN}]: " SMTP_FROM_INPUT
  SMTP_FROM="${SMTP_FROM_INPUT:-noreply@${DOMAIN}}"

  # --- Cloudflare Tunnel ---
  echo ""
  echo -e "${BLUE}Cloudflare Tunnel setup (optional)${NC}"
  echo "  A Cloudflare Tunnel lets you expose Nomii publicly without opening firewall ports."
  echo "  Create one at: dash.cloudflare.com > Zero Trust > Networks > Tunnels"
  echo "  Leave blank to skip (you can add it later in .env)."
  read -p "  Cloudflare Tunnel token: " CF_TOKEN

  # --- Stripe (optional) ---
  echo ""
  read -p "Set up Stripe billing now? [y/N] " SETUP_STRIPE
  if [[ "$SETUP_STRIPE" =~ ^[Yy]$ ]]; then
    read -p "  Stripe secret key (sk_live_...): " STRIPE_SECRET_KEY
    read -p "  Stripe webhook secret (whsec_...): " STRIPE_WEBHOOK_SECRET
    read -p "  Starter price ID: " STRIPE_PRICE_STARTER
    read -p "  Growth price ID: " STRIPE_PRICE_GROWTH
    read -p "  Professional price ID: " STRIPE_PRICE_PROFESSIONAL
  fi

  # --- Write .env ---
  cat > .env << ENVEOF
# Generated by install.sh on $(date)
# ============================================================

DB_PASSWORD=${DB_PASSWORD}
JWT_SECRET=${JWT_SECRET}
WIDGET_JWT_SECRET=${WIDGET_JWT_SECRET}
API_KEY_ENCRYPTION_SECRET=${API_KEY_ENCRYPTION_SECRET}

APP_URL=${APP_URL}
FRONTEND_URL=${APP_URL}
PORTAL_URL=${PORTAL_URL}

LLM_PROVIDER=claude
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
CLAUDE_API_KEY=${ANTHROPIC_API_KEY}

CLOUDFLARE_TUNNEL_TOKEN=${CF_TOKEN}

SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_SECURE=true
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_FROM=${SMTP_FROM}

MASTER_EMAIL=${MASTER_EMAIL}

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
STRIPE_PRICE_STARTER=${STRIPE_PRICE_STARTER:-}
STRIPE_PRICE_GROWTH=${STRIPE_PRICE_GROWTH:-}
STRIPE_PRICE_PROFESSIONAL=${STRIPE_PRICE_PROFESSIONAL:-}
STRIPE_PORTAL_RETURN_URL=${APP_URL}/dashboard/plans

LOGIN_RATE_LIMIT_MAX=3
WIDGET_SESSION_RATE_LIMIT_MAX=6
ENVEOF

  echo ""
  echo -e "${GREEN}✓ .env created${NC}"
fi

# ------------------------------------------------------------
# Step 2: Build and start containers
# ------------------------------------------------------------
echo ""
echo -e "${BLUE}Building and starting containers...${NC}"
echo "(This may take a few minutes on first run)"
echo ""

docker compose up --build -d

echo ""
echo -e "${GREEN}✓ Containers started${NC}"

# ------------------------------------------------------------
# Step 3: Run migrations
# ------------------------------------------------------------
echo ""
echo -e "${BLUE}Running database migrations...${NC}"
echo ""

bash "$SCRIPT_DIR/migrate.sh"

# ------------------------------------------------------------
# Done
# ------------------------------------------------------------
source .env 2>/dev/null || true

echo ""
echo -e "${BOLD}============================================================${NC}"
echo -e "${BOLD}${GREEN}  Nomii AI is running!${NC}"
echo -e "${BOLD}============================================================${NC}"
echo ""
echo -e "  Dashboard:  ${BLUE}${APP_URL:-http://localhost}${NC}"
echo -e "  API:        ${BLUE}${APP_URL:-http://localhost}:3001/api/health${NC}"
echo ""
echo -e "  Register your admin account at the dashboard"
echo -e "  using the email: ${BOLD}${MASTER_EMAIL}${NC}"
echo ""
echo -e "  To view logs:    ${BOLD}docker compose logs -f backend${NC}"
echo -e "  To stop:         ${BOLD}docker compose down${NC}"
echo -e "  To update:       ${BOLD}bash scripts/update.sh${NC}"
echo -e "  To backup DB:    ${BOLD}bash scripts/backup.sh${NC}"
echo ""
