/**
 * NOMII AI — Seed: Hope for This Nation tenant
 *
 * Creates the HFTN test tenant with Beacon as the AI companion,
 * generates a widget API key, and prints the embed snippet.
 *
 * Run:
 *   docker compose exec server node db/seed-hftn.js
 */

require('dotenv').config();
const fs   = require('fs');
const path = require('path');
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://nomii:nomii_dev_2026@localhost:5432/nomii_ai',
});

async function run() {
  console.log('\n🕊️  Seeding Hope for This Nation tenant...\n');

  const sql = fs.readFileSync(
    path.join(__dirname, 'seeds', '002_hope_for_this_nation.sql'),
    'utf-8'
  );
  await pool.query(sql);
  console.log('  ✓ Tenant and team leaders created');

  // Fetch the widget key (generated by the SQL above)
  const { rows } = await pool.query(
    `SELECT name, slug, widget_api_key, primary_color, agent_name
     FROM tenants WHERE id = '22222222-2222-2222-2222-222222222222'`
  );

  const tenant = rows[0];

  console.log(`  ✓ Tenant  : ${tenant.name}`);
  console.log(`  ✓ Slug    : ${tenant.slug}`);
  console.log(`  ✓ Agent   : ${tenant.agent_name}`);
  console.log(`  ✓ Color   : ${tenant.primary_color}`);
  console.log(`  ✓ Key     : ${tenant.widget_api_key}`);

  console.log(`
╔══════════════════════════════════════════════════════════════╗
║  EMBED SNIPPET FOR hub.hopeforthisnation.com                 ║
╚══════════════════════════════════════════════════════════════╝

Paste this into your Lovable project (replace YOUR_SERVER_URL):

<script
  src="https://YOUR_SERVER_URL/embed.js"
  data-widget-key="${tenant.widget_api_key}"
  data-user-email=""
  data-user-name=""
  data-primary-color="${tenant.primary_color}"
  data-label="Chat with Beacon"
></script>

The data-user-email and data-user-name should be populated
dynamically from your Supabase session (see Lovable prompt below).

──────────────────────────────────────────────────────────────

LOVABLE PROMPT (paste this into Lovable):

In the main layout that wraps authenticated pages, after the user
is confirmed logged in, dynamically inject a Shenmay AI chat widget.

Read the current user's email and display name from Supabase using
supabase.auth.getUser(). Then create a <script> element with these
attributes and append it to document.body:

  src:                "https://YOUR_SERVER_URL/embed.js"
  data-widget-key:    "${tenant.widget_api_key}"
  data-user-email:    (the user's email from Supabase)
  data-user-name:     (the user's display name, or email prefix if no name)
  data-primary-color: "${tenant.primary_color}"
  data-label:         "Chat with Beacon"

Only inject the script once per page load, and only when a user
session is active. Remove it on logout.

──────────────────────────────────────────────────────────────
`);

  await pool.end();
}

run().catch(err => {
  console.error('\n❌ Seed failed:', err.message);
  process.exit(1);
});
